#端口
server:
  port: 9006

spring:
  #redis连接配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 4

#mybatisplus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/lsjs/*.xml, classpath:mappers/SAPStoreHead/*.xml
  global-config:
    db-config:
      id-type: auto
